[build]
  command = "curl -LsSf https://astral.sh/uv/install.sh | sh && $HOME/.local/bin/uvx marimo export html-wasm authors.py --no-show-code -o dist/index.html"
  publish = "dist"

[build.environment]
  PYTHON_VERSION = "3.12"